[tool.poetry]
name = "testnet-manager"
version = "1.0.0"
description = "DevOps toolkit to operate Polkadot testnets"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
PyYAML = "^6.0"
APScheduler = "^3.9.1"
gunicorn = "^20.1.0"
uvicorn = "^0.18.2"
starlette = "^0.19.1"
kubernetes = "^24.2.0"
substrate-interface = "^1.2.8"
Jinja2 = "^3.1.2"
fastapi = "^0.79.0"

[tool.poetry.dev-dependencies]
testcontainers = "^3.6.1"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
